# # dataset
# dataset: 'camelyon17'
# data_dir: './Features/CAM17_res18'
# n_worker: 8
# n_class: 4
# pin_memory: True
# bs: 128
# B: 1                 # batch size
# train_transforms: ["resize", "flip", "rotate", "colorJitter", "totensor", "normalize"]
# val_transforms: ["resize", "totensor", "normalize"]
# n_shot: -1
# # model
# #backbone: 'ViT-B/16'
# backbone: 'Resnet18'
# #pretrain: 'medical_ssl'
# pretrain: 'natural_supervised'
# finetune: 'lp'
# D_feat: 512
# D_inner: 256

#dset
dataset: camelyon17
n_class: 4                            # number of classes
data_dir: './Features/CAM17_res18'       # directory of dataset
n_worker: 8                          # number of workers
pin_memory: False                     # use pin memory in dataloader
n_shot: -1
B: 1  
# pretrained
backbone: 'Resnet18'
pretrain: 'natural_supervised'
D_feat: 512
D_inner: 256

n_token: 4

# optim
optim: 'sgd'
wd: 0.0005
lr: 0.0001
min_lr: 0
augment_epoch: 1
warmup_epoch: 5
start_epoch: 0
train_epoch: 50

# other setting
load_head_checkpoints: False

heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: -1
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.4
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  # whether to use gaussian blur for further smoothing
  blur: True
  # whether to binarize attention scores
  binarize: false
  # factor for downscaling the heatmap before final dispaly
  custom_downsample: 1
  cmap: jet
